FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY scripts ./scripts

CMD ["node", "scripts/fake-feishu-server.mjs"]
